### PR TITLE
Integrate branch to master for pull request

### PR DESCRIPTION
**Pull request by Jakanis**

### CODE REVIEW

**Comment by Jakanis** [comment]
@Futurer fixed for python 3.5 and lower
Not sure how much lower as the lowest available Python for me - 3.5.

**Comment by Futurer** [comment]
Project: https://github.com/Kotlin/kotlin-koans

user@pc:~/Downloads/KotlinPyDoc-integration$ python3 KotlinPyDoc.py /home/user/Downloads/Test/Kotlin/kotlin-koans-master -r --output /home/user/Downloads/Kozii-1/
Traceback (most recent call last):
  File "KotlinPyDoc.py", line 208, in <module>
    parse(abspath, absoutput, args.recursive)
  File "KotlinPyDoc.py", line 189, in parse
    listElements = parsedir(abspath, absoutput, recursive)
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 144, in parsedir
    oneListElements = parsefile(join(abspath, file), absoutput)
  File "KotlinPyDoc.py", line 162, in parsefile
    resultingHTML, listElements = Documentor.parsefile(abspath, htmlHeader(join(pathToOutput,'index.html'),join(pathToOutput,'dir_doc.html'),join(pathToOutput,'abc.html')))
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 153, in parsefile
    listedElements, fileComment, fileImports = parseFileToList(filepath)
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 63, in parseFileToList
    name = re.findall('(?<=class )(\w+)', result[7]).pop()
IndexError: pop from empty list

**Comment by Futurer** [comment]
Project: https://github.com/ReactiveX/RxKotlin

user@pc:~/Downloads/KotlinPyDoc-integration$ python3 KotlinPyDoc.py /home/user/Downloads/Test/Kotlin/RxKotlin-2.x/ --output /home/user/Downloads/Kozii-4/ -r
Traceback (most recent call last):
  File "KotlinPyDoc.py", line 208, in <module>
    parse(abspath, absoutput, args.recursive)
  File "KotlinPyDoc.py", line 189, in parse
    listElements = parsedir(abspath, absoutput, recursive)
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  [Previous line repeated 3 more times]
  File "KotlinPyDoc.py", line 144, in parsedir
    oneListElements = parsefile(join(abspath, file), absoutput)
  File "KotlinPyDoc.py", line 162, in parsefile
    resultingHTML, listElements = Documentor.parsefile(abspath, htmlHeader(join(pathToOutput,'index.html'),join(pathToOutput,'dir_doc.html'),join(pathToOutput,'abc.html')))
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 154, in parsefile
    listedElements, fileComment, fileImports = parseFileToList(filepath)
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 54, in parseFileToList
    name = re.findall('[^\s]+(?=\()', result[5]).pop()
IndexError: pop from empty list

**Comment by Futurer** [comment]
src/i_introduction/_2_Named_Arguments/n02NamedArguments.kt_doc.html

**Comment by Futurer** [comment]
Project: https://github.com/Kotlin/kotlin-koans

user@pc:~/Downloads/KotlinPyDoc-integration$ python3 KotlinPyDoc.py -r /home/user/Downloads/Test/Kotlin/kotlin-koans-master/ --output /home/user/Downloads/Kozii-1/
Traceback (most recent call last):
  File "KotlinPyDoc.py", line 208, in <module>
    parse(abspath, absoutput, args.recursive)
  File "KotlinPyDoc.py", line 189, in parse
    listElements = parsedir(abspath, absoutput, recursive)
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 152, in parsedir
    listElements.extend(parsedir(join(abspath, dir), join(absoutput, dir),recursive))
  File "KotlinPyDoc.py", line 144, in parsedir
    oneListElements = parsefile(join(abspath, file), absoutput)
  File "KotlinPyDoc.py", line 162, in parsefile
    resultingHTML, listElements = Documentor.parsefile(abspath, htmlHeader(join(pathToOutput,'index.html'),join(pathToOutput,'dir_doc.html'),join(pathToOutput,'abc.html')))
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 159, in parsefile
    listedElements, fileComment, fileImports = parseFileToList(filepath)
  File "/home/user/Downloads/KotlinPyDoc-integration/Documentor.py", line 69, in parseFileToList
    name = re.findall('(?<=class )(\w+)', result[7]).pop()
IndexError: pop from empty list

**Pull request merged**
